### ISSUE TITLE
Comm Radio state doesn't refresh on open

### ISSUE THREAD

**Issue by lassombra** [fauxnik/dv-comms-radio-api#7]
So it took a bit for me to figure this one out and it's still entirely possible _I'm_ doing something wrong.

When the comm radio gets put away and then pulled back out while on the mode registered through this api - the mode appears to reset it's internal state, but doesn't appear to update the screen.

I resolved this experimentally in my own local environment by changing the Enable function here:
https://github.com/fauxnik/dv-comms-radio-api/blob/696880e76e897b5f81419dc92f1e9a76b3c95c44/CommsRadioAPI/CommsRadioMode.cs#L99 to 

`	public void Enable()
	{
		activeState = startingState;
		if (null != activeState)
		{
			ApplyState();
			activeState.OnEnter(proxy, null);
		}
	}`

Doing so caused the screen to update as expected.  I'm not sure if this is the preferred way to solve this, but it does resolve the issue of the screen and state being out of sync until the next state is triggered (in my case by a raycast)

**Comment by fauxnik** [comment]
Finally getting around to fixing this. Thanks for reporting it @lassombra! ❤️ I would've done it sooner if I'd not somehow overlooked that you showed the solution in your issue text. My bad. 😅
